USE [RentaCar]
GO

/****** Object:  Table [dbo].[Furnizimi]    Script Date: 6/1/2018 11:49:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Furnizimi](
	[FurnizimiID] [int] IDENTITY(1,1) NOT NULL,
	[Furnizimi] [varchar](50) NOT NULL,
 CONSTRAINT [PK_FurnizimiID_1] PRIMARY KEY CLUSTERED 
(
	[FurnizimiID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


