USE [RentaCar]
GO

/****** Object:  Table [dbo].[Statusi]    Script Date: 6/1/2018 11:51:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Statusi](
	[StatusiID] [int] IDENTITY(1,1) NOT NULL,
	[Statusi] [varchar](50) NOT NULL,
 CONSTRAINT [PK_StatusiID_1] PRIMARY KEY CLUSTERED 
(
	[StatusiID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


