/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.RegjistroHuazimet;
import DAL.RegjistroPuntorinException;
import DAL.RegjistroHuzimetInterface;
import DAL.RegjistroHuazimetRepository;
import Model.RegjistroHuazimetTableModel;
import java.sql.SQLException;
import java.util.List;
import DAL.Lidhja;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author
 */
public class RegjistroHuzimetForm extends javax.swing.JInternalFrame {
    
    Lidhja l=new Lidhja();
    RegjistroHuazimetRepository regjistroHuazimetRepository = new RegjistroHuazimetRepository();
    RegjistroHuazimetTableModel regjistroHuazimetTableModel = new RegjistroHuazimetTableModel();

    /**
     * Creates new form RegjistroPuntorinForm
     */
     private void gjeneroCombo(){
       
         try{
             
        String s = "select l.Llojivetures,v.Modeli,v.Ngjyra,v.CmimiVeturespernjediteRent from RegjistroVeturen v, Llojivetures l where v.LlojiveturesID=l.LlojiveturesID";
      l.st = l.cn.prepareStatement(s);
       l.rs = l.st.executeQuery();
        while(l.rs.next())
        { 
           this.txtVetura.addItem(l.rs.getString("Llojivetures")+" "+l.rs.getString("Modeli")+" "+l.rs.getString("Ngjyra")+" "+l.rs.getString("CmimiVeturespernjediteRent"));
        }
         l.st.close();
         l.rs.close();
         }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "ERROR te culonat");
    }
         
          try{
             
        String s = "select Emri,Mbiemri,NrPersonal from RegjistroKlientin";
      l.st = l.cn.prepareStatement(s);
       l.rs = l.st.executeQuery();
        while(l.rs.next())
        { 
           this.txtKlienti.addItem(l.rs.getString("Emri")+" "+l.rs.getString("Mbiemri")+" "+l.rs.getString("NrPersonal"));
        }
         l.st.close();
         l.rs.close();
         }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "ERROR te culonat");
    }
     }
    public RegjistroHuzimetForm() {
        initComponents();
        tabelaLoad();
        gjeneroCombo();
                
    }

    public void emptyObject() {
        tabela.clearSelection();
        txtVetura.setSelectedItem("");
        txtKlienti.setSelectedItem("");    
        jDatahuazimit.setDate(null);
        jDateKthimit.setDate(null);
        qqCmimi.setText("");
     
         
        
    }
    public String Split(String s, int index){
        String[]strn=s.split("\\s+");
      String result=strn[index];
        return result;     
    }

    
    public String llogarit(Date date1, Date date2){
        RegjistroHuazimet rh = new RegjistroHuazimet();
        float f=0;
        
        long d1 = (date1.getTime() - date2.getTime()) ;
        
        String ss=(Split((String)txtVetura.getSelectedItem(),3));
        f=(d1 / (1000*60*60*24));
        f*=Float.parseFloat(ss);
        return String.valueOf(f);
    }

    private void tabelaLoad() {
        List<RegjistroHuazimet> lista = regjistroHuazimetRepository.findAll();
        regjistroHuazimetTableModel.add(lista);
        tabela.setModel(regjistroHuazimetTableModel);
        regjistroHuazimetTableModel.fireTableDataChanged();
        tabelaSelectedIndexChange();

    }

    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    RegjistroHuazimet regjistroHuazimet = regjistroHuazimetTableModel.getRegjistroHuazimet(selectedIndex);
                    
                    jDatahuazimit.setDate(regjistroHuazimet.getDataHuazimit());
                    jDateKthimit.setDate(regjistroHuazimet.getDataKthimit());
                   qqCmimi.setText(llogarit(regjistroHuazimet.getDataKthimit(),regjistroHuazimet.getDataHuazimit()));
                  
                    
                   
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDatahuazimit = new com.toedter.calendar.JDateChooser();
        jDateKthimit = new com.toedter.calendar.JDateChooser();
        txtVetura = new javax.swing.JComboBox<>();
        txtKlienti = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        qqCmimi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(194, 212, 212));
        setClosable(true);
        setMaximizable(true);
        setTitle("Regjistro Huazimet");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data Huazimit");

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Ruaje");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Fshije");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Anulo");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data  Kthimit");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Klientit");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Vetura");

        txtVetura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeturaActionPerformed(evt);
            }
        });

        txtKlienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKlientiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cmimi :");

        qqCmimi.setBackground(new java.awt.Color(102, 102, 102));
        qqCmimi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qqCmimi.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtVetura, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDatahuazimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qqCmimi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 301, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtKlienti, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateKthimit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVetura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKlienti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateKthimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addComponent(jDatahuazimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qqCmimi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            int row = tabela.getSelectedRow();
            if (jDatahuazimit.getDate().equals("")) {
                JOptionPane.showMessageDialog(this, "Caktoni Daten e Huazimit ! :", "Error", JOptionPane.ERROR_MESSAGE);

            } else if (jDateKthimit.getDate().equals("")) {
                JOptionPane.showMessageDialog(this, "Caktoni Daten e Kthimit !  :", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (row == -1) {
                    RegjistroHuazimet regjistroHuazimet = new RegjistroHuazimet();
                    
                    regjistroHuazimet.setEmriKlientit(Split((String)txtKlienti.getSelectedItem(),0));
                    regjistroHuazimet.setMbiemriKlientit(Split((String)txtKlienti.getSelectedItem(),1));
                    regjistroHuazimet.setNrPersonal(Split((String)txtKlienti.getSelectedItem(),2));
                    regjistroHuazimet.setLlojivetures(Split((String)txtVetura.getSelectedItem(),0));
                    regjistroHuazimet.setModeli(Split((String)txtVetura.getSelectedItem(),1));
                    regjistroHuazimet.setNgjyra(Split((String)txtVetura.getSelectedItem(),2));
                    regjistroHuazimet.setRentnDit(Split((String)txtVetura.getSelectedItem(),3));
                    regjistroHuazimet.setDataHuazimit(jDatahuazimit.getDate());
                    regjistroHuazimet.setDataKthimit(jDateKthimit.getDate());
                    qqCmimi.setText(llogarit(regjistroHuazimet.getDataKthimit(),regjistroHuazimet.getDataHuazimit()));
                    regjistroHuazimet.setCmimi(Float.parseFloat(qqCmimi.getText()));

                    regjistroHuazimetRepository.create(regjistroHuazimet);
                    JOptionPane.showMessageDialog(this, "E dhëna u ruajt me sukses !");
                } else {
                    RegjistroHuazimet regjistroHuazimet = this.regjistroHuazimetTableModel.getRegjistroHuazimet(row);
                  
                    regjistroHuazimet.setEmriKlientit(Split((String)txtKlienti.getSelectedItem(),0));        
                    regjistroHuazimet.setMbiemriKlientit(Split((String)txtKlienti.getSelectedItem(),1));
                    regjistroHuazimet.setNrPersonal(Split((String)txtKlienti.getSelectedItem(),2));
                    regjistroHuazimet.setLlojivetures(Split((String)txtVetura.getSelectedItem(),0));
                    regjistroHuazimet.setModeli(Split((String)txtVetura.getSelectedItem(),1));
                    regjistroHuazimet.setNgjyra(Split((String)txtVetura.getSelectedItem(),2));
                    regjistroHuazimet.setRentnDit(Split((String)txtVetura.getSelectedItem(),3));
                    regjistroHuazimet.setDataHuazimit(jDatahuazimit.getDate());
                    regjistroHuazimet.setDataKthimit(jDateKthimit.getDate());
                    qqCmimi.setText(llogarit(regjistroHuazimet.getDataKthimit(),regjistroHuazimet.getDataHuazimit()));
                    regjistroHuazimet.setCmimi(Float.parseFloat(qqCmimi.getText()));
                    
                    regjistroHuazimetRepository.edit(regjistroHuazimet);
                    JOptionPane.showMessageDialog(this, "E dhëna u editua me sukses");
                }
                emptyObject();
                tabelaLoad();
            }

        } catch (RegjistroPuntorinException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            int row = tabela.getSelectedRow();
            if(row > -1){
                Object [] ob = {"Po","Jo"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta fshini ?", "Fshirja", JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if(i==0){
                    RegjistroHuazimet regjistroHuazimet = this.regjistroHuazimetTableModel.getRegjistroHuazimet(row);
                    regjistroHuazimetRepository.remove(regjistroHuazimet);
                    tabelaLoad();
                    emptyObject();
                    JOptionPane.showMessageDialog(this, "E dhëna është fshir me sukses !");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Nuk keni selektuar asgjë për të fshir !");
            }
        }catch(RegjistroPuntorinException pe){
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        emptyObject();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtVeturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVeturaActionPerformed

    private void txtKlientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKlientiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKlientiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDatahuazimit;
    private com.toedter.calendar.JDateChooser jDateKthimit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel qqCmimi;
    private javax.swing.JTable tabela;
    private javax.swing.JComboBox<String> txtKlienti;
    private javax.swing.JComboBox<String> txtVetura;
    // End of variables declaration//GEN-END:variables
}
